print('<!DOCTYPE html>')
print('<html>')
print('<head>')
print('    <meta charset="utf-8">')
print('    <title>私のホームページ</title>')
print('</head>')
print('    <body bgcolor="#00FFFF">')
print('        <p>私のホームページへようこそ！</p>')
print('    </body>')
print('</html>')