content = 'Hatsune Miku,sometimesreferredtoasMikuHatsune,isthenameofaVocaloidsoftwarevoicebankdevelopedbyCryptonFutureMediaanditsofficialmoeanthropomorphism,a16-year-oldgirlwithlong,turquoisetwintails.SheusesYamahaCorporationsVocaloid2,Vocaloid3,andVocaloid4singingsynthesizingtechnologies.ShealsouseCryptonFutureMediasPiaproStudio,asingingsynthesizerVSTiPlugin.ShewasthesecondVocaloidsoldusingtheVocaloid2engineandthefirstJapaneseVocaloidtousetheJapaneseversionoftheVocaloid2engine.HervoiceismodeledfromJapanesevoiceactressSakiFujita.HatsuneMikuspersonificationhasbeenmarketedaavirtualidolandhasperformedatconcertsonstageasananimatedprojectio(rearcastprojectiononaspeciallycoatedglassscreen).'
a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z = content.count('a'),content.count('b'),content.count('c'),content.count('d'),content.count('e'),content.count('f'),content.count('g'),content.count('h'),content.count('i'),content.count('j'),content.count('k'),content.count('l'),content.count('m'),content.count('n'),content.count('o'),content.count('p'),content.count('q'),content.count('r'),content.count('s'),content.count('t'),content.count('u'),content.count('v'),content.count('w'),content.count('x'),content.count('y'),content.count('z')

a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z = content.count('a'),content.count('b'),content.count('c'),content.count('d'),content.count('e'),content.count('f'),content.count('g'),content.count('h'),content.count('i'),content.count('j'),content.count('k'),content.count('l'),content.count('m'),content.count('n'),content.count('o'),content.count('p'),content.count('q'),content.count('r'),content.count('s'),content.count('t'),content.count('u'),content.count('v'),content.count('w'),content.count('x'),content.count('y'),content.count('z')

print('contentに代入されてる文章内に含まれるアルファベットの出現回数を調べます')
print('a：' + str(a))
print('b：' + str(b))
print('c：' + str(c))
print('d：' + str(d))
print('e：' + str(e))
print('f：' + str(f))
print('g：' + str(g))
print('h：' + str(h))
print('i：' + str(i))
print('j：' + str(j))
print('k：' + str(k))
print('l：' + str(l))
print('m：' + str(m))
print('n：' + str(n))
print('o：' + str(o))
print('p：' + str(p))
print('q：' + str(q))
print('r：' + str(r))
print('s：' + str(s))
print('t：' + str(t))
print('u：' + str(u))
print('v：' + str(v))
print('w：' + str(w))
print('x：' + str(x))
print('y：' + str(y))
print('z：' + str(z))
