1.SELECT LOWER(ename) AS 小文字 FROM emp;

2.SELECT LOWER(dname) AS DNAME,UPPER(dname) AS DNAME,INITCAP(LOC) AS LOC FROM dept;

3.SELECT INITCAP('AA AA_AA:AA') FROM dual;
SELECT INITCAP('taro@k-tera.ac.jp') FROM dual;

4.SELECT LOWER(first_name) AS FIRST_NAME, UPPER(last_name) AS LAST_NAME,INITCAP(JOB_ID) AS JOB_ID FROM person;

5.SELECT LOWER( UPPER( INITCAP(job_id))) FROM person;